In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_excel("./Dry_Bean_Dataset.xlsx")

In [7]:
df = pd.read_csv("./haberman.csv", header=None)

In [10]:
df

      0   1  2  3
0    30  64  1  1
1    30  62  3  1
2    30  65  0  1
3    31  59  2  1
4    31  65  4  1
..   ..  .. .. ..
301  75  62  1  1
302  76  67  0  1
303  77  65  3  1
304  78  65  1  2
305  83  58  2  2

[306 rows x 4 columns]

In [11]:
np.unique(df[3].values, return_counts=True)

(array([1, 2], dtype=int64), array([225,  81], dtype=int64))

In [38]:
df.head(3)

,Area,Perimeter,MajorAxisLength,MinorAxisLength,AspectRation,Eccentricity,ConvexArea,EquivDiameter,Extent,Solidity,roundness,Compactness,ShapeFactor1,ShapeFactor2,ShapeFactor3,ShapeFactor4,Class,labels
0,28395,610.291,208.178117,173.888747,1.197191,0.549812,28715,190.141097,0.763923,0.988856,0.958027,0.913358,0.007332,0.003147,0.834222,0.998724,SEKER,0
1,28734,638.018,200.524796,182.734419,1.097356,0.411785,29172,191.272750,0.783968,0.984986,0.887034,0.953861,0.006979,0.003564,0.909851,0.998430,SEKER,0
2,29380,624.110,212.826130,175.931143,1.209713,0.562727,29690,193.410904,0.778113,0.989559,0.947849,0.908774,0.007244,0.003048,0.825871,0.999066,SEKER,0

In [37]:
u, u_c = np.unique(df.iloc[:, -1].values, return_index=True)
u = u[np.argsort(u_c)]

In [35]:
df["labels"] = 0

In [41]:
for i, name in enumerate(u):
    df.loc[df["Class"] == name, "labels"] = i
df.drop("Class", axis=1, inplace=True)

In [42]:
df.head()

,Area,Perimeter,MajorAxisLength,MinorAxisLength,AspectRation,Eccentricity,ConvexArea,EquivDiameter,Extent,Solidity,roundness,Compactness,ShapeFactor1,ShapeFactor2,ShapeFactor3,ShapeFactor4,labels
0,28395,610.291,208.178117,173.888747,1.197191,0.549812,28715,190.141097,0.763923,0.988856,0.958027,0.913358,0.007332,0.003147,0.834222,0.998724,0
1,28734,638.018,200.524796,182.734419,1.097356,0.411785,29172,191.272750,0.783968,0.984986,0.887034,0.953861,0.006979,0.003564,0.909851,0.998430,0
2,29380,624.110,212.826130,175.931143,1.209713,0.562727,29690,193.410904,0.778113,0.989559,0.947849,0.908774,0.007244,0.003048,0.825871,0.999066,0
3,30008,645.884,210.557999,182.516516,1.153638,0.498616,30724,195.467062,0.782681,0.976696,0.903936,0.928329,0.007017,0.003215,0.861794,0.994199,0
4,30140,620.134,201.847882,190.279279,1.060798,0.333680,30417,195.896503,0.773098,0.990893,0.984877,0.970516,0.006697,0.003665,0.941900,0.999166,0

In [24]:
np.unique(df[7].values)

array([1, 2, 3], dtype=int64)

In [10]:
np.unique(df[3].values)

array([1, 2], dtype=int64)